//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteFinderApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        public int CollegeID { get; set; }
        public string CollegeName { get; set; }
        public string DLINumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string ContactDetails { get; set; }
        public int NumOfCourses { get; set; }
        public int NumOfCampus { get; set; }
    }
}
