//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteFinderApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string CollegeName { get; set; }
        public string CourseLength { get; set; }
        public int NumofLevels { get; set; }
        public string CampusOffering { get; set; }
        public string DLINumber { get; set; }
    }
}
